### ISSUE TITLE
将 UserName 转换成 userName

### ISSUE THREAD

**Issue by mualala** [tekintian/go-str-utils#1]
请问将 UserName 转换成 userName 用哪个方法呢？我试了一下没找到合适的方法

**Comment by tekintian** [comment]
将 UserName 转换成 userName  这种是属于将大驼峰转换为小驼峰命名, 使用 SmallCamelStr 这个函数，详细文档见
https://pkg.go.dev/github.com/tekintian/strutils#SmallCamelStr

命名转换相关的函数源码 https://github.com/tekintian/strutils/blob/main/naming_convert.go
